language: java
sudo: false

jdk:
  - oraclejdk11

services:
  - docker

before_install:
  - docker run -d --name ci_db -p 3307:3306 -e MYSQL_DATABASE=parser_test -e MYSQL_ROOT_PASSWORD=root mysql:5.7.26

after_install:
  - docker stop ci_db
  - docker rm ci_db

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - sh mvnw clean install

cache:
  directories:
    - "$HOME/.m2"
